"""Userfiles

Revision ID: 618299244a36
Revises: 6c97bdcc3b78
Create Date: 2025-04-19 16:55:25.591913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '618299244a36'
down_revision: Union[str, None] = '6c97bdcc3b78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('vector_ids', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('platform_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_team_id_platform_name', 'user_files', ['team_id', 'platform_name'], unique=False)
    op.create_unique_constraint(None, 'file_storage', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file_storage', type_='unique')
    op.drop_index('ix_team_id_platform_name', table_name='user_files')
    op.drop_table('user_files')
    # ### end Alembic commands ###
