"""Init

Revision ID: 6c97bdcc3b78
Revises: 
Create Date: 2025-04-06 20:58:16.755624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c97bdcc3b78'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('integration_name', sa.String(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_team_app_integration_user', 'api_keys', ['team_id', 'app_name', 'integration_name', 'user_id'], unique=False)
    op.create_table('file_storage',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('lists',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('list_name', sa.String(), nullable=False),
    sa.Column('list_contents', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_team_user_listname', 'lists', ['team_id', 'user_id', 'list_name'], unique=True)
    op.create_table('oauth_tokens',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('integration_type', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index('ix_team_app_integration_user_outh', 'oauth_tokens', ['team_id', 'app_name', 'integration_type', 'user_id'], unique=False)
    op.create_table('slack_tokens',
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('bot_user_id', sa.String(), nullable=False),
    sa.Column('bot_access_token', sa.String(), nullable=False),
    sa.Column('is_enterprise_install', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_index('ix_team_id', 'slack_tokens', ['team_id'], unique=False)
    op.create_table('users',
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('app_team_id', sa.String(), nullable=False),
    sa.Column('app_user_id', sa.String(), nullable=False),
    sa.Column('associated_google_email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('app_name', 'app_team_id', 'app_user_id')
    )
    op.create_index('idx_app_name', 'users', ['app_name'], unique=False)
    op.create_index('idx_app_team_id', 'users', ['app_team_id'], unique=False)
    op.create_index('idx_app_user_id', 'users', ['app_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_app_user_id', table_name='users')
    op.drop_index('idx_app_team_id', table_name='users')
    op.drop_index('idx_app_name', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_team_id', table_name='slack_tokens')
    op.drop_table('slack_tokens')
    op.drop_index('ix_team_app_integration_user_outh', table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index('ix_team_user_listname', table_name='lists')
    op.drop_table('lists')
    op.drop_table('file_storage')
    op.drop_index('ix_team_app_integration_user', table_name='api_keys')
    op.drop_table('api_keys')
    # ### end Alembic commands ###
